// Configuração das camadas do WebGIS Paranapiacaba.
// Foco: corredor ferroviário histórico Jundiaí–Santos (São Paulo Railway) e a
// Vila de Paranapiacaba (Santo André). Os arquivos GeoJSON em public/data/ são
// gerados pelo pipeline em scripts/ (ver scripts/build_data.py).
//
// Campos: id, label, file, group, type, color, weight, fillOpacity, minZoom,
//         visible, cluster (agrupar pontos), popupFields, description, available.

export const LAYERS = [
  // ============ FERROVIA SPR (JUNDIAÍ–SANTOS) — eixo do projeto ============
  {
    id: "ferrovia_corredor",
    label: "Corredor Ferroviário Jundiaí–Santos",
    file: "ferrovia_corredor.geojson",
    group: "Ferrovia SPR (Jundiaí–Santos)",
    type: "line",
    color: "#1E293B",
    weight: 3,
    minZoom: 8,
    visible: true,
    popupFields: [],
    description: "Malha ferroviária histórica da São Paulo Railway (1867) e sucessoras, de Jundiaí à Baixada Santista, base IBGE (BaseFerro). Estilizada por situação operacional.",
    available: true
  },
  {
    id: "estacoes",
    label: "Estações Ferroviárias",
    file: "estacoes.geojson",
    group: "Ferrovia SPR (Jundiaí–Santos)",
    type: "point",
    color: "#0EA5E9",
    minZoom: 9,
    visible: true,
    cluster: true,
    popupFields: [],
    description: "Estações ao longo do corredor Jundiaí–Santos (base IBGE), incluindo Paranapiacaba.",
    available: true
  },
  {
    id: "ferrovia_local",
    label: "Leito Ferroviário (Vila)",
    file: "ferrovia_local.geojson",
    group: "Ferrovia SPR (Jundiaí–Santos)",
    type: "line",
    color: "#6D6875",
    weight: 2,
    minZoom: 14,
    visible: false,
    popupFields: [],
    description: "Traçado detalhado dos trilhos no núcleo da Vila de Paranapiacaba (cadastro georreferenciado).",
    available: true
  },
  {
    id: "funicular",
    label: "Leito do Funicular",
    file: "funicular.geojson",
    group: "Ferrovia SPR (Jundiaí–Santos)",
    type: "line",
    color: "#B5838D",
    weight: 2,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Leito inclinado do Funicular da Serra do Mar (Serra Velha de 1867 e Serra Nova de 1901) — sítio histórico-industrial sob interdição.",
    available: true
  },
  {
    id: "patrimonio_ferroviario",
    label: "Ruínas / Patrimônio Ferroviário",
    file: "patrimonio_ferroviario.geojson",
    group: "Ferrovia SPR (Jundiaí–Santos)",
    type: "polygon",
    color: "#BC6C25",
    weight: 1,
    fillOpacity: 0.4,
    minZoom: 14,
    visible: false,
    popupFields: [],
    description: "Ruínas e estruturas remanescentes do complexo ferroviário da Vila.",
    available: true
  },

  // ====================== MOBILIDADE ======================
  {
    id: "ferrovia_rmsp",
    label: "Ferrovias RMSP (CPTM/Metrô)",
    file: "ferrovia_rmsp.geojson",
    group: "Mobilidade",
    type: "line",
    color: "#0891B2",
    weight: 2,
    minZoom: 9,
    visible: false,
    popupFields: [],
    description: "Linhas ferroviárias metropolitanas (CPTM/Metrô) na RMSP — base CEM 2021.",
    available: true
  },
  {
    id: "rodovias",
    label: "Rodovias",
    file: "rodovias.geojson",
    group: "Mobilidade",
    type: "line",
    color: "#CA8A04",
    weight: 1.5,
    minZoom: 9,
    visible: false,
    popupFields: [],
    description: "Malha rodoviária estrutural da RMSP (base CEM 2021).",
    available: true
  },
  {
    id: "ciclovias",
    label: "Ciclovias",
    file: "ciclovias.geojson",
    group: "Mobilidade",
    type: "line",
    color: "#16A34A",
    weight: 2,
    minZoom: 13,
    visible: false,
    popupFields: [],
    description: "Sistema cicloviário de Santo André.",
    available: true
  },
  {
    id: "mobilidade_urbana",
    label: "Linhas de Ônibus",
    file: "mobilidade_urbana.geojson",
    group: "Mobilidade",
    type: "line",
    color: "#0D9488",
    weight: 1.2,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Linhas de ônibus municipais e intermunicipais (base SIGA/MUR), coloridas por tipo.",
    available: true
  },

  // ====================== TERRITÓRIO ======================
  {
    id: "limite_sitio",
    label: "Limite do Sítio (Alto da Serra)",
    file: "limite_sitio.geojson",
    group: "Território",
    type: "polygon",
    color: "#E63946",
    weight: 2.5,
    fillOpacity: 0.05,
    minZoom: 11,
    visible: true,
    popupFields: [],
    description: "Perímetro de estudo do Alto da Serra / Paranapiacaba (delimitação FAPESP).",
    available: true
  },
  {
    id: "limite_vila",
    label: "ZEIP Paranapiacaba (Vila)",
    file: "limite_vila.geojson",
    group: "Território",
    type: "polygon",
    color: "#E63946",
    weight: 1.5,
    fillOpacity: 0.08,
    minZoom: 13,
    visible: false,
    popupFields: [],
    description: "Zona Especial de Interesse do Patrimônio (ZEIP) da Vila ferroviária, fundada em 1867 pela São Paulo Railway.",
    available: true
  },
  {
    id: "municipios_corredor",
    label: "Municípios do Corredor",
    file: "municipios_corredor.geojson",
    group: "Território",
    type: "polygon",
    color: "#64748B",
    weight: 1,
    fillOpacity: 0.04,
    minZoom: 8,
    visible: false,
    popupFields: [],
    description: "Municípios atravessados pelo corredor ferroviário Jundiaí–Santos (IBGE 2024).",
    available: true
  },
  {
    id: "grande_abc",
    label: "Região do Grande ABC",
    file: "grande_abc.geojson",
    group: "Território",
    type: "polygon",
    color: "#475569",
    weight: 1.5,
    fillOpacity: 0.04,
    minZoom: 8,
    visible: false,
    popupFields: [],
    description: "Municípios da Região do Grande ABC paulista.",
    available: true
  },
  {
    id: "bairros",
    label: "Bairros (Santo André)",
    file: "bairros.geojson",
    group: "Território",
    type: "polygon",
    color: "#8B5CF6",
    weight: 0.8,
    fillOpacity: 0.06,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Bairros oficiais do município de Santo André.",
    available: true
  },
  {
    id: "parque_andreense",
    label: "Parque Andreense",
    file: "parque_andreense.geojson",
    group: "Território",
    type: "polygon",
    color: "#15803D",
    weight: 1.5,
    fillOpacity: 0.12,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "Perímetro do Parque Andreense (Área de Proteção Ambiental municipal).",
    available: true
  },

  // ====================== PATRIMÔNIO ======================
  {
    id: "patrimonio_tombados",
    label: "Bens Tombados",
    file: "patrimonio_tombados.geojson",
    group: "Patrimônio",
    type: "polygon",
    color: "#E9C46A",
    weight: 1,
    fillOpacity: 0.4,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "Bens tombados nas instâncias federal (IPHAN), estadual (CONDEPHAAT) e municipal (COMDEPHAAPASA), por instância.",
    available: true
  },
  {
    id: "bens_registrados",
    label: "Bens Registrados (Imaterial)",
    file: "bens_registrados.geojson",
    group: "Patrimônio",
    type: "point",
    color: "#D97706",
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Bens culturais registrados (patrimônio imaterial) de Santo André.",
    available: true
  },
  {
    id: "territorios_culturais",
    label: "Territórios Culturais",
    file: "territorios_culturais.geojson",
    group: "Patrimônio",
    type: "polygon",
    color: "#A855F7",
    weight: 1,
    fillOpacity: 0.2,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Territórios culturais delimitados no município.",
    available: true
  },
  {
    id: "edificacoes_vila",
    label: "Edificações da Vila (por uso)",
    file: "edificacoes_vila.geojson",
    group: "Patrimônio",
    type: "polygon",
    color: "#F4A261",
    weight: 0.8,
    fillOpacity: 0.5,
    minZoom: 15,
    visible: false,
    popupFields: [],
    description: "Edificações inventariadas da Vila, classificadas por uso (residencial, comercial, hotelaria, público, etc.).",
    available: true
  },
  {
    id: "bens_estudo",
    label: "Bens em Estudo (tombamento)",
    file: "bens_estudo.geojson",
    group: "Patrimônio",
    type: "polygon",
    color: "#C084FC",
    weight: 1,
    fillOpacity: 0.25,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Bens culturais em processo de estudo para tombamento (COMDEPHAAPASA) — etapa anterior ao tombamento formal.",
    available: true
  },
  {
    id: "abpf",
    label: "Área ABPF (preservação ferroviária)",
    file: "abpf.geojson",
    group: "Patrimônio",
    type: "polygon",
    color: "#92400E",
    weight: 1.5,
    fillOpacity: 0.18,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Área da Associação Brasileira de Preservação Ferroviária (ABPF), ligada à operação histórica da ferrovia.",
    available: true
  },

  // ====================== MORFOLOGIA DA VILA ======================
  {
    id: "edificacoes_cad",
    label: "Edificações — traçado CAD (2025)",
    file: "edificacoes_cad.geojson",
    group: "Morfologia da Vila",
    type: "line",
    color: "#78716C",
    weight: 0.8,
    minZoom: 15,
    visible: false,
    popupFields: [],
    description: "Contorno das edificações da Vila no levantamento CAD oficial (DWG \"Mapa Vila 2025 UNESCO\"), georreferenciado.",
    available: true
  },
  {
    id: "sistema_viario",
    label: "Sistema Viário (Vila)",
    file: "sistema_viario.geojson",
    group: "Morfologia da Vila",
    type: "line",
    color: "#A8A29E",
    weight: 1.2,
    minZoom: 15,
    visible: false,
    popupFields: [],
    description: "Traçado das vias do núcleo urbano de Paranapiacaba (levantamento CAD 2025 georreferenciado).",
    available: true
  },
  {
    id: "caminhos_vila",
    label: "Caminhos da Vila",
    file: "caminhos_vila.geojson",
    group: "Morfologia da Vila",
    type: "line",
    color: "#CA8A04",
    weight: 1.5,
    minZoom: 15,
    visible: false,
    popupFields: [],
    description: "Caminhos e percursos de pedestres mapeados no núcleo da Vila (base Palazzi).",
    available: true
  },
  {
    id: "curvas_nivel",
    label: "Curvas de Nível (Vila)",
    file: "curvas_nivel.geojson",
    group: "Morfologia da Vila",
    type: "line",
    color: "#B45309",
    weight: 0.6,
    minZoom: 15,
    visible: false,
    popupFields: [],
    description: "Curvas de nível detalhadas do núcleo da Vila — base para análise do relevo da escarpa (levantamento CAD 2025).",
    available: true
  },
  {
    id: "pac_lotes",
    label: "Lotes / Cadastro da Vila",
    file: "pac_lotes.geojson",
    group: "Morfologia da Vila",
    type: "line",
    color: "#E76F51",
    weight: 1,
    fillOpacity: 0.35,
    minZoom: 15,
    visible: false,
    popupFields: [],
    description: "Lotes do cadastro georreferenciado da Vila ferroviária (base para o PAC Cidades Históricas).",
    available: true
  },

  // ====================== MEIO AMBIENTE ======================
  {
    id: "ucs",
    label: "Unidades de Conservação",
    file: "ucs.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#2D6A4F",
    weight: 1.5,
    fillOpacity: 0.15,
    minZoom: 9,
    visible: false,
    popupFields: [],
    description: "Unidades de Conservação estaduais e municipais (PESM Núcleo Itutinga-Pilões, Alto da Serra e outras).",
    available: true
  },
  {
    id: "reservatorios",
    label: "Reservatórios (RMSP)",
    file: "reservatorios.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#0EA5E9",
    weight: 0.8,
    fillOpacity: 0.4,
    minZoom: 9,
    visible: false,
    popupFields: [],
    description: "Reservatórios e represas da RMSP (Billings, Guarapiranga e outros).",
    available: true
  },
  {
    id: "subbacias",
    label: "Sub-bacias (divisor de águas)",
    file: "subbacias.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#0E7490",
    weight: 1.5,
    fillOpacity: 0.12,
    minZoom: 10,
    visible: false,
    popupFields: [],
    description: "Sub-bacias ao redor da Vila — divisor de águas entre o Alto Tietê (UGRHI 6) e a Baixada Santista/Rio Cubatão (UGRHI 7).",
    available: true
  },
  {
    id: "regioes_hidrograficas",
    label: "Regiões Hidrográficas",
    file: "regioes_hidrograficas.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#0369A1",
    weight: 1.5,
    fillOpacity: 0.08,
    minZoom: 9,
    visible: false,
    popupFields: [],
    description: "Grandes regiões hidrográficas (ex.: Alto Tietê e Baixada Santista) que se encontram no divisor de águas da Serra do Mar.",
    available: true
  },
  {
    id: "hidrografia",
    label: "Hidrografia (Córregos)",
    file: "hidrografia.geojson",
    group: "Meio Ambiente",
    type: "line",
    color: "#4895EF",
    weight: 1.5,
    minZoom: 13,
    visible: false,
    popupFields: [],
    description: "Rede de drenagem da Vila — divisor de águas Cubatão (vertente sul) / Tietê (vertente norte).",
    available: true
  },
  {
    id: "nascentes",
    label: "Nascentes",
    file: "nascentes.geojson",
    group: "Meio Ambiente",
    type: "point",
    color: "#52B788",
    minZoom: 14,
    visible: false,
    popupFields: [],
    description: "Pontos de surgência mapeados, fundamentais para a bacia hidrográfica local.",
    available: true
  },
  {
    id: "app_buffers",
    label: "APPs (corpos hídricos)",
    file: "app_buffers.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#4CC9F0",
    weight: 0.5,
    fillOpacity: 0.2,
    minZoom: 14,
    visible: false,
    popupFields: [],
    description: "Áreas de Preservação Permanente ao redor de córregos e nascentes.",
    available: true
  },
  {
    id: "declividade",
    label: "Classes de Declividade",
    file: "declividade.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#8338EC",
    weight: 0,
    fillOpacity: 0.35,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Classes de declividade da escarpa (em breve — derivação a partir de MDT).",
    available: false
  },

  // ====================== TURISMO E TRILHAS ======================
  {
    id: "trilhas",
    label: "Trilhas (Wikiloc)",
    file: "trilhas.geojson",
    group: "Turismo e Trilhas",
    type: "line",
    color: "#FB5607",
    weight: 2,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "46 trilhas reais mapeadas por GPS (Wikiloc), ~793 km, com distância e desnível acumulado, coloridas por região (Quilombo, Cachoeiras, Funicular, Rio Mogi, Quatinga).",
    available: true
  },
  {
    id: "atrativos",
    label: "Atrativos Naturais",
    file: "atrativos.geojson",
    group: "Turismo e Trilhas",
    type: "point",
    color: "#FF9F1C",
    minZoom: 12,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "243 atrativos naturais extraídos dos waypoints GPS Wikiloc: 115 cachoeiras, 50 poços, 30 pedras, 30 mirantes, 7 ruínas, 6 nascentes e 5 grutas.",
    available: true
  },
  {
    id: "circuitos",
    label: "Circuitos Turísticos",
    file: "circuitos.geojson",
    group: "Turismo e Trilhas",
    type: "point",
    color: "#FFBF69",
    minZoom: 13,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "Pontos dos circuitos turísticos de Santo André (city tour histórico, arte e arquitetura, etc.).",
    available: true
  },

  // ====================== LEGISLAÇÃO E PLANEJAMENTO ======================
  {
    id: "macrozonas",
    label: "Macrozonas (LC 1.181/2022)",
    file: "macrozonas.geojson",
    group: "Legislação e Planejamento",
    type: "polygon",
    color: "#0D9488",
    weight: 1,
    fillOpacity: 0.2,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "Macrozonas do Plano Diretor de Santo André (Lei Complementar 1.181/2022).",
    available: true
  },
  {
    id: "zoneamento_mzpa",
    label: "Setorização MZPA",
    file: "zoneamento_mzpa.geojson",
    group: "Legislação e Planejamento",
    type: "polygon",
    color: "#7C3AED",
    weight: 0.8,
    fillOpacity: 0.2,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Setorização da Macrozona de Proteção Ambiental (MZPA).",
    available: true
  },

  // ====================== SOCIOECONOMIA ======================
  {
    id: "censo_setores",
    label: "Setores Censitários (Paranapiacaba)",
    file: "censo_setores.geojson",
    group: "Socioeconomia",
    type: "polygon",
    color: "#9B5DE5",
    weight: 0.8,
    fillOpacity: 0.3,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Setores censitários do distrito de Paranapiacaba (IBGE).",
    available: true
  },
  {
    id: "densidade",
    label: "Densidade Demográfica",
    file: "densidade.geojson",
    group: "Socioeconomia",
    type: "polygon",
    color: "#F15BB5",
    weight: 0,
    fillOpacity: 0.5,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Densidade demográfica (hab/ha) por setor censitário no distrito de Paranapiacaba.",
    available: true
  },

  // ====================== EQUIPAMENTOS URBANOS ======================
  {
    id: "saude",
    label: "Saúde",
    file: "saude.geojson",
    group: "Equipamentos Urbanos",
    type: "point",
    color: "#EF4444",
    minZoom: 10,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "Equipamentos de saúde (UBS, UPA, hospitais, SAMU, CAPS) no corredor.",
    available: true
  },
  {
    id: "educacao",
    label: "Educação",
    file: "educacao.geojson",
    group: "Equipamentos Urbanos",
    type: "point",
    color: "#3B82F6",
    minZoom: 10,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "Equipamentos de educação (creches, EMEI/EMEIEF, escolas estaduais, ensino superior) no corredor.",
    available: true
  },
  {
    id: "seguranca",
    label: "Segurança",
    file: "seguranca.geojson",
    group: "Equipamentos Urbanos",
    type: "point",
    color: "#6366F1",
    minZoom: 10,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "Equipamentos de segurança (GCM, polícia, bombeiros) no corredor.",
    available: true
  },
  {
    id: "esporte",
    label: "Esporte",
    file: "esporte.geojson",
    group: "Equipamentos Urbanos",
    type: "point",
    color: "#10B981",
    minZoom: 10,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "Equipamentos esportivos e atividades de esporte no corredor.",
    available: true
  },
  {
    id: "assistencia_social",
    label: "Assistência Social",
    file: "assistencia_social.geojson",
    group: "Equipamentos Urbanos",
    type: "point",
    color: "#EC4899",
    minZoom: 10,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "Equipamentos de assistência social (CRAS, CREAS, centros de convivência).",
    available: true
  },
  {
    id: "defesa_civil",
    label: "Defesa Civil",
    file: "defesa_civil.geojson",
    group: "Equipamentos Urbanos",
    type: "point",
    color: "#F97316",
    minZoom: 10,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "Abrigos e pluviômetros da Defesa Civil no corredor.",
    available: true
  },
  {
    id: "feiras_livres",
    label: "Feiras Livres",
    file: "feiras_livres.geojson",
    group: "Equipamentos Urbanos",
    type: "line",
    color: "#DB2777",
    weight: 3,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Logradouros onde ocorrem feiras livres (base CRAISA), com dia e horário de funcionamento.",
    available: true
  },
  {
    id: "cemiterio",
    label: "Cemitérios",
    file: "cemiterio.geojson",
    group: "Equipamentos Urbanos",
    type: "point",
    color: "#57534E",
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Cemitérios municipais, incluindo o Cemitério Bom Jesus de Paranapiacaba.",
    available: true
  }
];

// Auxiliar para agrupar as camadas por grupo (preserva a ordem de declaração)
export const GROUPS = [...new Set(LAYERS.map(layer => layer.group))];
