// Configuração das camadas do WebGIS Paranapiacaba.
// Foco: corredor ferroviário histórico Jundiaí–Santos (São Paulo Railway) e a
// Vila de Paranapiacaba (Santo André). Os arquivos GeoJSON em public/data/ são
// gerados pelo pipeline em scripts/ (ver scripts/build_data.py).
//
// Campos: id, label, file, group, type, color, weight, fillOpacity, minZoom,
//         visible, cluster (agrupar pontos), popupFields, description, available.

export const LAYERS = [
  // ============ FERROVIA SPR (JUNDIAÍ–SANTOS) — eixo do projeto ============
  {
    id: "ferrovia_corredor",
    label: "Corredor Ferroviário Jundiaí–Santos",
    file: "ferrovia_corredor.geojson",
    group: "Ferrovia SPR (Jundiaí–Santos)",
    type: "line",
    color: "#1E293B",
    weight: 3,
    minZoom: 8,
    visible: true,
    popupFields: [],
    description: "Malha ferroviária histórica da São Paulo Railway (1867) e sucessoras, de Jundiaí à Baixada Santista, base IBGE (BaseFerro). Estilizada por situação operacional.",
    available: true
  },
  {
    id: "estacoes",
    label: "Estações Ferroviárias",
    file: "estacoes.geojson",
    group: "Ferrovia SPR (Jundiaí–Santos)",
    type: "point",
    color: "#595959",
    minZoom: 9,
    visible: true,
    cluster: true,
    popupFields: [],
    description: "Estações ao longo do corredor Jundiaí–Santos (base IBGE), incluindo Paranapiacaba.",
    available: true
  },
  {
    id: "ferrovia_local",
    label: "Leito Ferroviário (Vila)",
    file: "ferrovia_local.geojson",
    group: "Ferrovia SPR (Jundiaí–Santos)",
    type: "line",
    color: "#6D6875",
    weight: 2,
    minZoom: 14,
    visible: false,
    popupFields: [],
    description: "Traçado detalhado dos trilhos no núcleo da Vila de Paranapiacaba (cadastro georreferenciado).",
    available: true
  },
  {
    id: "funicular",
    label: "Leito do Funicular",
    file: "funicular.geojson",
    group: "Ferrovia SPR (Jundiaí–Santos)",
    type: "line",
    color: "#B5838D",
    weight: 2,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Leito inclinado do Funicular da Serra do Mar (Serra Velha de 1867 e Serra Nova de 1901) — sítio histórico-industrial sob interdição.",
    available: true
  },
  {
    id: "patrimonio_ferroviario",
    label: "Ruínas / Patrimônio Ferroviário",
    file: "patrimonio_ferroviario.geojson",
    group: "Ferrovia SPR (Jundiaí–Santos)",
    type: "polygon",
    color: "#BC6C25",
    weight: 1,
    fillOpacity: 0.4,
    minZoom: 14,
    visible: false,
    popupFields: [],
    description: "Ruínas e estruturas remanescentes do complexo ferroviário da Vila.",
    available: true
  },

  // ====================== MOBILIDADE ======================
  {
    id: "ferrovia_rmsp",
    label: "Ferrovias RMSP (CPTM/Metrô)",
    file: "ferrovia_rmsp.geojson",
    group: "Mobilidade",
    type: "line",
    color: "#0891B2",
    weight: 2,
    minZoom: 9,
    visible: false,
    popupFields: [],
    description: "Linhas ferroviárias metropolitanas (CPTM/Metrô) na RMSP — base CEM 2021.",
    available: true
  },
  {
    id: "rodovias",
    label: "Rodovias",
    file: "rodovias.geojson",
    group: "Mobilidade",
    type: "line",
    color: "#CA8A04",
    weight: 1.5,
    minZoom: 9,
    visible: false,
    popupFields: [],
    description: "Malha rodoviária estrutural da RMSP (base CEM 2021).",
    available: true
  },
  {
    id: "ciclovias",
    label: "Ciclovias",
    file: "ciclovias.geojson",
    group: "Mobilidade",
    type: "line",
    color: "#16A34A",
    weight: 2,
    minZoom: 13,
    visible: false,
    popupFields: [],
    description: "Sistema cicloviário de Santo André.",
    available: true
  },
  {
    id: "mobilidade_urbana",
    label: "Linhas de Ônibus",
    file: "mobilidade_urbana.geojson",
    group: "Mobilidade",
    type: "line",
    color: "#0D9488",
    weight: 1.2,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Linhas de ônibus municipais e intermunicipais (base SIGA/MUR), coloridas por tipo.",
    available: true
  },

  // ====================== TERRITÓRIO ======================
  {
    id: "limite_sitio",
    label: "Limite do Sítio (Alto da Serra)",
    file: "limite_sitio.geojson",
    group: "Território",
    type: "polygon",
    color: "#E63946",
    weight: 2.5,
    fillOpacity: 0.05,
    minZoom: 11,
    visible: true,
    popupFields: [],
    description: "Perímetro de estudo do Alto da Serra / Paranapiacaba (delimitação FAPESP).",
    available: true
  },
  {
    id: "limite_vila",
    label: "ZEIP Paranapiacaba (Vila)",
    file: "limite_vila.geojson",
    group: "Território",
    type: "polygon",
    color: "#8B4513",
    weight: 2,
    fillOpacity: 0.05,
    minZoom: 13,
    visible: false,
    popupFields: [],
    description: "Zona Especial de Interesse do Patrimônio (ZEIP) da Vila ferroviária, fundada em 1867 pela São Paulo Railway.",
    available: true
  },
  {
    id: "municipios_corredor",
    label: "Municípios do Corredor",
    file: "municipios_corredor.geojson",
    group: "Território",
    type: "polygon",
    color: "#64748B",
    weight: 1,
    fillOpacity: 0.04,
    minZoom: 8,
    visible: false,
    popupFields: [],
    description: "Municípios atravessados pelo corredor ferroviário Jundiaí–Santos (IBGE 2024).",
    available: true
  },
  {
    id: "grande_abc",
    label: "Região do Grande ABC",
    file: "grande_abc.geojson",
    group: "Território",
    type: "polygon",
    color: "#475569",
    weight: 1.5,
    fillOpacity: 0.04,
    minZoom: 8,
    visible: false,
    popupFields: [],
    description: "Municípios da Região do Grande ABC paulista.",
    available: true
  },
  {
    id: "bairros",
    label: "Bairros (Santo André)",
    file: "bairros.geojson",
    group: "Território",
    type: "polygon",
    color: "#8B5CF6",
    weight: 0.8,
    fillOpacity: 0.06,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Bairros oficiais do município de Santo André.",
    available: true
  },
  {
    id: "parque_andreense",
    label: "Parque Andreense",
    file: "parque_andreense.geojson",
    group: "Território",
    type: "polygon",
    color: "#15803D",
    weight: 1.5,
    fillOpacity: 0.12,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "Perímetro do Parque Andreense (Área de Proteção Ambiental municipal).",
    available: true
  },
  {
    id: "distritos",
    label: "Distritos / Subdistritos",
    file: "distritos.geojson",
    group: "Território",
    type: "polygon",
    color: "#475569",
    weight: 1.5,
    fillOpacity: 0.04,
    minZoom: 10,
    visible: false,
    popupFields: [],
    description: "Distritos e subdistritos de Santo André, incluindo o distrito de Paranapiacaba.",
    available: true
  },

  // ====================== PATRIMÔNIO ======================
  {
    id: "patrimonio_tombados",
    label: "Bens Tombados (IPHAN / Condephaat)",
    file: "patrimonio_tombados.geojson",
    group: "Patrimônio",
    type: "polygon",
    color: "#581845",
    weight: 2.5,
    fillOpacity: 0,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "Bens tombados nas instâncias federal (IPHAN - Vinho), estadual (CONDEPHAAT - Carmim) e municipal (COMDEPHAAPASA - Vermelho). Exibidos com contornos vazios conforme padrão IBGE.",
    available: true
  },
  {
    id: "bens_registrados",
    label: "Bens Registrados (Imaterial)",
    file: "bens_registrados.geojson",
    group: "Patrimônio",
    type: "point",
    color: "#D97706",
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Bens culturais registrados (patrimônio imaterial) de Santo André.",
    available: true
  },
  {
    id: "territorios_culturais",
    label: "Territórios Culturais",
    file: "territorios_culturais.geojson",
    group: "Patrimônio",
    type: "polygon",
    color: "#A855F7",
    weight: 1,
    fillOpacity: 0.2,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Territórios culturais delimitados no município.",
    available: true
  },
  {
    id: "edificacoes_vila",
    label: "Edificações da Vila (Uso / Conservação)",
    file: "edificacoes_vila.geojson",
    group: "Patrimônio",
    type: "polygon",
    color: "#FCE4D6",
    weight: 0.8,
    fillOpacity: 0.6,
    minZoom: 15,
    visible: false,
    popupFields: [],
    description: "Edificações da Vila classificadas por uso e estado de conservação (escala semáforo IBGE: conservado, mau estado, descaracterizado, ruínas).",
    available: true
  },
  {
    id: "bens_estudo",
    label: "Bens em Estudo (tombamento)",
    file: "bens_estudo.geojson",
    group: "Patrimônio",
    type: "polygon",
    color: "#C084FC",
    weight: 1,
    fillOpacity: 0.25,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Bens culturais em processo de estudo para tombamento (COMDEPHAAPASA) — etapa anterior ao tombamento formal.",
    available: true
  },
  {
    id: "abpf",
    label: "Área ABPF (preservação ferroviária)",
    file: "abpf.geojson",
    group: "Patrimônio",
    type: "polygon",
    color: "#E1BEE7",
    weight: 1.5,
    fillOpacity: 0.2,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Área da Associação Brasileira de Preservação Ferroviária (ABPF) — turismo/cultura.",
    available: true
  },
  {
    id: "areas_envoltorias",
    label: "Áreas Envoltórias (Proposta UNESCO)",
    file: "areas_envoltorias.geojson",
    group: "Patrimônio",
    type: "polygon",
    color: "#D4AF37",
    weight: 2,
    fillOpacity: 0,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "Zonas de entorno / amortecimento para a candidatura UNESCO — borda dourada tracejada sem preenchimento.",
    available: true
  },

  // ====================== MORFOLOGIA DA VILA ======================
  {
    id: "edificacoes_cad",
    label: "Edificações — traçado CAD (2025)",
    file: "edificacoes_cad.geojson",
    group: "Morfologia da Vila",
    type: "line",
    color: "#78716C",
    weight: 0.8,
    minZoom: 15,
    visible: false,
    popupFields: [],
    description: "Contorno das edificações da Vila no levantamento CAD oficial (DWG \"Mapa Vila 2025 UNESCO\"), georreferenciado.",
    available: true
  },
  {
    id: "sistema_viario",
    label: "Sistema Viário (Vila)",
    file: "sistema_viario.geojson",
    group: "Morfologia da Vila",
    type: "line",
    color: "#A8A29E",
    weight: 1.2,
    minZoom: 15,
    visible: false,
    popupFields: [],
    description: "Traçado das vias do núcleo urbano de Paranapiacaba (levantamento CAD 2025 georreferenciado).",
    available: true
  },
  {
    id: "caminhos_vila",
    label: "Caminhos da Vila",
    file: "caminhos_vila.geojson",
    group: "Morfologia da Vila",
    type: "line",
    color: "#CA8A04",
    weight: 1.5,
    minZoom: 15,
    visible: false,
    popupFields: [],
    description: "Caminhos e percursos de pedestres mapeados no núcleo da Vila (base Palazzi).",
    available: true
  },
  {
    id: "curvas_nivel",
    label: "Curvas de Nível (Vila)",
    file: "curvas_nivel.geojson",
    group: "Morfologia da Vila",
    type: "line",
    color: "#833C0C",
    weight: 0.6,
    minZoom: 15,
    visible: false,
    popupFields: [],
    description: "Curvas de nível detalhadas do núcleo da Vila em tom sépia (#833C0C) — exibição em escalas locais (>= 1:5.000).",
    available: true
  },
  {
    id: "pac_lotes",
    label: "Lotes / Cadastro da Vila",
    file: "pac_lotes.geojson",
    group: "Morfologia da Vila",
    type: "line",
    color: "#E76F51",
    weight: 1,
    fillOpacity: 0.35,
    minZoom: 15,
    visible: false,
    popupFields: [],
    description: "Lotes do cadastro georreferenciado da Vila ferroviária (base para o PAC Cidades Históricas).",
    available: true
  },

  // ====================== MEIO AMBIENTE ======================
  {
    id: "ucs",
    label: "Unidades de Conservação (Rebio / Parques)",
    file: "ucs.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#4B5320",
    weight: 2,
    fillOpacity: 0,
    minZoom: 9,
    visible: false,
    popupFields: [],
    description: "Unidades de Conservação estaduais e municipais (PESM Núcleo Itutinga-Pilões, Rebio Alto da Serra e outras) em borda Verde Oliva sem preenchimento.",
    available: true
  },
  {
    id: "reservatorios",
    label: "Reservatórios (RMSP)",
    file: "reservatorios.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#0EA5E9",
    weight: 0.8,
    fillOpacity: 0.4,
    minZoom: 9,
    visible: false,
    popupFields: [],
    description: "Reservatórios e represas da RMSP (Billings, Guarapiranga e outros).",
    available: true
  },
  {
    id: "subbacias",
    label: "Sub-bacias (divisor de águas)",
    file: "subbacias.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#0E7490",
    weight: 1.5,
    fillOpacity: 0.12,
    minZoom: 10,
    visible: false,
    popupFields: [],
    description: "Sub-bacias ao redor da Vila — divisor de águas entre o Alto Tietê (UGRHI 6) e a Baixada Santista/Rio Cubatão (UGRHI 7).",
    available: true
  },
  {
    id: "regioes_hidrograficas",
    label: "Regiões Hidrográficas",
    file: "regioes_hidrograficas.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#0369A1",
    weight: 1.5,
    fillOpacity: 0.08,
    minZoom: 9,
    visible: false,
    popupFields: [],
    description: "Grandes regiões hidrográficas (ex.: Alto Tietê e Baixada Santista) que se encontram no divisor de águas da Serra do Mar.",
    available: true
  },
  {
    id: "hidrografia",
    label: "Hidrografia (Córregos)",
    file: "hidrografia.geojson",
    group: "Meio Ambiente",
    type: "line",
    color: "#0070C0",
    weight: 1.5,
    minZoom: 13,
    visible: false,
    popupFields: [],
    description: "Rede de drenagem da Vila — divisor de águas Cubatão / Tietê em Azul Hídrico exclusivo (#0070C0).",
    available: true
  },
  {
    id: "nascentes",
    label: "Nascentes",
    file: "nascentes.geojson",
    group: "Meio Ambiente",
    type: "point",
    color: "#0070C0",
    minZoom: 14,
    visible: false,
    popupFields: [],
    description: "Pontos de surgência hídrica mapeados (#0070C0).",
    available: true
  },
  {
    id: "app_buffers",
    label: "APPs (corpos hídricos)",
    file: "app_buffers.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#A9D08E",
    weight: 0.8,
    fillOpacity: 0.4,
    minZoom: 14,
    visible: false,
    popupFields: [],
    description: "Áreas de Preservação Permanente ao redor de córregos e nascentes em Verde Claro (#A9D08E com 40% de opacidade).",
    available: true
  },
  {
    id: "classif_vegetal",
    label: "Vegetação (Mata Atlântica)",
    file: "classif_vegetal.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#385723",
    weight: 0.5,
    fillOpacity: 0.45,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "Cobertura vegetal em Verde Floresta Escuro (#385723 - base IBGE), classificada por estágio de sucessão da Mata Atlântica.",
    available: true
  },
  {
    id: "app_sul",
    label: "APPs (Serra / vertente Sul)",
    file: "app_sul.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#A9D08E",
    weight: 0.8,
    fillOpacity: 0.4,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "Áreas de Preservação Permanente da vertente Sul em Verde Claro (#A9D08E com 40% de opacidade).",
    available: true
  },
  {
    id: "rios_sul",
    label: "Rios (Serra / vertente Sul)",
    file: "rios_sul.geojson",
    group: "Meio Ambiente",
    type: "line",
    color: "#0070C0",
    weight: 1.2,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Rede hidrográfica da vertente Sul da Serra do Mar em Azul Hídrico (#0070C0).",
    available: true
  },
  {
    id: "pnm_nascentes",
    label: "PNM Nascentes de Paranapiacaba",
    file: "pnm_nascentes.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#1B4332",
    weight: 1.5,
    fillOpacity: 0.18,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "Parque Natural Municipal Nascentes de Paranapiacaba — unidade de conservação municipal.",
    available: true
  },
  {
    id: "altimetria_serra",
    label: "Altimetria da Serra (Curvas 50 m)",
    file: "altimetria_serra.geojson",
    group: "Meio Ambiente",
    type: "line",
    color: "#833C0C",
    weight: 0.6,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Curvas-mestras de altitude (a cada 50 m) em tom sépia (#833C0C) — para visualização regional sem poluição.",
    available: true
  },
  {
    id: "billings_747",
    label: "Represa Billings (cota 747)",
    file: "billings_747.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#0EA5E9",
    weight: 1,
    fillOpacity: 0.3,
    minZoom: 10,
    visible: false,
    popupFields: [],
    description: "Espelho d'água da Represa Billings na cota 747 — contexto do manancial regional.",
    available: true
  },
  {
    id: "declividade",
    label: "Classes de Declividade",
    file: "declividade.geojson",
    group: "Meio Ambiente",
    type: "polygon",
    color: "#8338EC",
    weight: 0,
    fillOpacity: 0.35,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Classes de declividade da escarpa (em breve — derivação a partir de MDT).",
    available: false
  },

  // ====================== RISCOS (DEFESA CIVIL) ======================
  {
    id: "susc_movmas",
    label: "Suscetibilidade a Deslizamentos (2025)",
    file: "susc_movmas.geojson",
    group: "Riscos (Defesa Civil)",
    type: "polygon",
    color: "#EF4444",
    weight: 0.8,
    fillOpacity: 0.4,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "Suscetibilidade a movimentos de massa (deslizamentos) — IPT 2025, por grau (R3 alto, R4 muito alto, SM monitoramento).",
    available: true
  },
  {
    id: "risco_movmas",
    label: "Risco de Deslizamento (2014)",
    file: "risco_movmas.geojson",
    group: "Riscos (Defesa Civil)",
    type: "polygon",
    color: "#DC2626",
    weight: 0.8,
    fillOpacity: 0.4,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "Setores de risco a movimentos de massa mapeados pelo IPT (2014), por grau (R2–R4).",
    available: true
  },
  {
    id: "risco_incendio",
    label: "Risco de Incêndio",
    file: "risco_incendio.geojson",
    group: "Riscos (Defesa Civil)",
    type: "polygon",
    color: "#EA580C",
    weight: 0.6,
    fillOpacity: 0.4,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "Áreas classificadas por risco de incêndio (Defesa Civil), por grau (R3, R4, SM).",
    available: true
  },

  // ====================== TURISMO E TRILHAS ======================
  {
    id: "trilhas",
    label: "Trilhas (Wikiloc)",
    file: "trilhas.geojson",
    group: "Turismo e Trilhas",
    type: "line",
    color: "#FB5607",
    weight: 2,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "46 trilhas reais mapeadas por GPS (Wikiloc), ~793 km, com distância e desnível acumulado, coloridas por região (Quilombo, Cachoeiras, Funicular, Rio Mogi, Quatinga).",
    available: true
  },
  {
    id: "atrativos",
    label: "Atrativos Naturais",
    file: "atrativos.geojson",
    group: "Turismo e Trilhas",
    type: "point",
    color: "#FF9F1C",
    minZoom: 12,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "243 atrativos naturais extraídos dos waypoints GPS Wikiloc: 115 cachoeiras, 50 poços, 30 pedras, 30 mirantes, 7 ruínas, 6 nascentes e 5 grutas.",
    available: true
  },
  {
    id: "circuitos",
    label: "Circuitos Turísticos",
    file: "circuitos.geojson",
    group: "Turismo e Trilhas",
    type: "point",
    color: "#FFBF69",
    minZoom: 13,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "Pontos dos circuitos turísticos de Santo André (city tour histórico, arte e arquitetura, etc.).",
    available: true
  },

  // ====================== LEGISLAÇÃO E PLANEJAMENTO ======================
  {
    id: "macrozonas",
    label: "Macrozonas (LC 1.181/2022)",
    file: "macrozonas.geojson",
    group: "Legislação e Planejamento",
    type: "polygon",
    color: "#0D9488",
    weight: 1,
    fillOpacity: 0.2,
    minZoom: 11,
    visible: false,
    popupFields: [],
    description: "Macrozonas do Plano Diretor de Santo André (Lei Complementar 1.181/2022).",
    available: true
  },
  {
    id: "zoneamento_mzpa",
    label: "Setorização MZPA",
    file: "zoneamento_mzpa.geojson",
    group: "Legislação e Planejamento",
    type: "polygon",
    color: "#7C3AED",
    weight: 0.8,
    fillOpacity: 0.2,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Setorização da Macrozona de Proteção Ambiental (MZPA).",
    available: true
  },

  // ====================== SOCIOECONOMIA ======================
  {
    id: "censo_setores",
    label: "Setores Censitários (Paranapiacaba)",
    file: "censo_setores.geojson",
    group: "Socioeconomia",
    type: "polygon",
    color: "#9B5DE5",
    weight: 0.8,
    fillOpacity: 0.3,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Setores censitários do distrito de Paranapiacaba (IBGE).",
    available: true
  },
  {
    id: "densidade",
    label: "Densidade Demográfica",
    file: "densidade.geojson",
    group: "Socioeconomia",
    type: "polygon",
    color: "#F15BB5",
    weight: 0,
    fillOpacity: 0.5,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Densidade demográfica (hab/ha) por setor censitário no distrito de Paranapiacaba.",
    available: true
  },
  {
    id: "densidade_2022",
    label: "Densidade Demográfica (2022)",
    file: "densidade_2022.geojson",
    group: "Socioeconomia",
    type: "polygon",
    color: "#F15BB5",
    weight: 0.6,
    fillOpacity: 0.35,
    minZoom: 10,
    visible: false,
    popupFields: [],
    description: "Densidade demográfica por bairro de Santo André (Censo IBGE 2022).",
    available: true
  },
  {
    id: "populacao_2022",
    label: "População (Censo 2022)",
    file: "populacao_2022.geojson",
    group: "Socioeconomia",
    type: "polygon",
    color: "#C026D3",
    weight: 0.6,
    fillOpacity: 0.35,
    minZoom: 10,
    visible: false,
    popupFields: [],
    description: "População total por bairro de Santo André (Censo IBGE 2022).",
    available: true
  },

  // ====================== EQUIPAMENTOS URBANOS ======================
  {
    id: "saude",
    label: "Saúde",
    file: "saude.geojson",
    group: "Equipamentos Urbanos",
    type: "point",
    color: "#EF4444",
    minZoom: 10,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "Equipamentos de saúde (UBS, UPA, hospitais, SAMU, CAPS) no corredor.",
    available: true
  },
  {
    id: "educacao",
    label: "Educação",
    file: "educacao.geojson",
    group: "Equipamentos Urbanos",
    type: "point",
    color: "#BDD7EE",
    minZoom: 10,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "Equipamentos de educação no tom Azul Claro Serviços IBGE (#BDD7EE).",
    available: true
  },
  {
    id: "rede_eletrica",
    label: "Rede de Eletricidade",
    file: "rede_eletrica.geojson",
    group: "Equipamentos Urbanos",
    type: "line",
    color: "#FF0000",
    weight: 1.5,
    minZoom: 13,
    visible: false,
    popupFields: [],
    description: "Infraestrutura de energia elétrica em linha tracejada Vermelho Vivo (#FF0000) — em breve.",
    available: false
  },
  {
    id: "seguranca",
    label: "Segurança",
    file: "seguranca.geojson",
    group: "Equipamentos Urbanos",
    type: "point",
    color: "#6366F1",
    minZoom: 10,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "Equipamentos de segurança (GCM, polícia, bombeiros) no corredor.",
    available: true
  },
  {
    id: "esporte",
    label: "Esporte",
    file: "esporte.geojson",
    group: "Equipamentos Urbanos",
    type: "point",
    color: "#10B981",
    minZoom: 10,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "Equipamentos esportivos e atividades de esporte no corredor.",
    available: true
  },
  {
    id: "assistencia_social",
    label: "Assistência Social",
    file: "assistencia_social.geojson",
    group: "Equipamentos Urbanos",
    type: "point",
    color: "#EC4899",
    minZoom: 10,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "Equipamentos de assistência social (CRAS, CREAS, centros de convivência).",
    available: true
  },
  {
    id: "defesa_civil",
    label: "Defesa Civil",
    file: "defesa_civil.geojson",
    group: "Equipamentos Urbanos",
    type: "point",
    color: "#F97316",
    minZoom: 10,
    visible: false,
    cluster: true,
    popupFields: [],
    description: "Abrigos e pluviômetros da Defesa Civil no corredor.",
    available: true
  },
  {
    id: "feiras_livres",
    label: "Feiras Livres",
    file: "feiras_livres.geojson",
    group: "Equipamentos Urbanos",
    type: "line",
    color: "#DB2777",
    weight: 3,
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Logradouros onde ocorrem feiras livres (base CRAISA), com dia e horário de funcionamento.",
    available: true
  },
  {
    id: "cemiterio",
    label: "Cemitérios",
    file: "cemiterio.geojson",
    group: "Equipamentos Urbanos",
    type: "point",
    color: "#57534E",
    minZoom: 12,
    visible: false,
    popupFields: [],
    description: "Cemitérios municipais, incluindo o Cemitério Bom Jesus de Paranapiacaba.",
    available: true
  }
];

// Auxiliar para agrupar as camadas por grupo (preserva a ordem de declaração)
export const GROUPS = [...new Set(LAYERS.map(layer => layer.group))];
